import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import assets from '../lib/assets'
import styles from '../styles/Home.module.css'

function Hero() {
  const [imageLoaded, setImageLoaded] = useState(false);
  useEffect(() => {
    const image = new Image();
    image.src = '/basith.jpg';
    image.onload = function() {
      setImageLoaded(true)
    };
  }, []);
  return <div className={styles.hero}>
    <div className={[styles.intro].concat(imageLoaded ? styles.ready: []).join(' ')}>
      <div>
        <div>
          <h1><span className={styles.reveal}>Basith</span><br /><span className={styles.reveal}>Kunimal</span></h1>
        </div>
        <div>
          <h2 className={styles.reveal}>Fullstack Developer</h2>
        </div>
      </div>
    </div>
    <div className={styles.backgrounds}>
      <div className={styles.profile}>
        <div className={styles.clipContainer}>
          <div className={styles.clip}></div>
        </div>
        <div className={styles.iconsContainer}>
          <div className={styles.icons}>
            {assets.map((f, key) => {
              const index = parseInt(key, 10) / assets.length
              const r = 300;
              const left = 250 + r * Math.cos(2 * Math.PI * index);
              const top = 250 + r * Math.sin(2 * Math.PI * index);
              return React.cloneElement(f, {
                key,
                style: { left, top },
              })
            })}
          </div>
        </div>
      </div>
    </div>
  </div>
}

function Intro() {
  return <div className={styles.hero}>
    <div style={{ width: '40%' }}>

    </div>
    <div className={styles.intro} style={{ flex: 1 }}>

    </div>
  </div>
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Basith Kunimal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <Intro />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
